version: '3'

services:
  backend:
    container_name: erp_backend
    image: erp_backend
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://erp_user:Erp123456!@erp_postgres:5432/erp_saas"
      VITE_API_URL: "https://144.126.150.74.com"
      SECRET_KEY: "mysecretkey"
    networks:
      - backend-network

  postgres:
    container_name: erp_postgres
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "erp_user"
      POSTGRES_PASSWORD: "Erp123456!"
      POSTGRES_DB: "erp_saas"
    networks:
      - backend-network

networks:
  default: 
    driver: bridge